@PROT=https
@HOST=httpbin.org
@SITE={{PROT}}://{{HOST}}

###

{{SITE}}/get

### with method

GET {{SITE}}/get

### with http version

GET {{SITE}}/get HTTP/1.1

###

POST {{SITE}}/post
Content-Type:

{
  "key": "value"
}
