@PROT=https
@HOST=httpbin.org
@Address={{PROT}}://{{HOST}}

### get

{{Address}}/get

### method

GET {{Address}}/get

### http version

GET {{Address}}/get HTTP/1.1

### env

{{EnvAddress}}/get

### user env

{{UserEnvAddress}}/get

### post

POST {{Address}}/post
Content-Type: application/json

{
  "key": "value"
}
